---
title: "qPCR Summary"
author: "Felix Westcott"
date: "2022-07-28"
output: html_document
---

```{r setup, include=MediaLSE}
library(tidyverse)
library(ggplot2)
library(readxl)
library(xlsx)
library(dplyr)
library(ggpubr)
library(ggsci)
library(rstatix)
library (cowplot)
library (ggprism)

qPCR_summary <- read_excel("HNM qPCR Summary.xlsx", sheet = 2)

qPCR_summary$"Condition" <- factor(qPCR_summary$"Condition", levels = c("LPS Control",	"Low Insulin Control", "Low Insulin OPLA", "Low Insulin POLA", "High Insulin Control", "High Insulin OPLA", "High Insulin POLA"))

qPCR_summary$"Round" <- as.numeric(qPCR_summary$"Round", levels = c("1", "2", "3"))

qPCR_summary <- filter(qPCR_summary, Condition != "LPS Control")

```

``` {R Stats}

for (i in 9:ncol(qPCR_summary)) {
   formula <- as.formula(paste(colnames(qPCR_summary)[i], " ~ Condition", sep=""))
   model <- aov(formula, data = qPCR_summary)
   
   Tukey <- TukeyHSD(model)
   Tukey <- separate(
  as.tibble(Tukey$Condition, rownames = "Condition"), 
  Condition, into = c("group1", "group2"), sep = "-", convert = TRUE)
   Tukey <- filter(Tukey, Tukey$`p adj` < 0.05)

   cat("\n-----\n\n")
   cat(colnames(qPCR_summary)[i])
   cat("\n")
   print(summary(model))
   print(Tukey)
}

```
``` {R}

ggbarplot(qPCR_summary, x = "Condition", "CASP3",
       add = "mean_se", error.plot = "upper_errorbar", palette = "npg", legend = "none", fill = "Condition", xlab = " ", ylab = "Relative Expression") +
   theme_prism(base_size = 14) +
  theme(legend.position = "none") +
    scale_x_discrete(labels = function(x) str_wrap(x, width = 10)) +
      scale_y_continuous(expand = expansion(mult = c(0, 0.1)))
ggsave('C:/Users/fwestcott/OneDrive - Nexus365/Desktop/Outputs/Transfer-report/Figures/HNM CASP3.png')

qPCR_summary_Tidy <- pivot_longer(qPCR_summary[,c(2,14,16,17,20)], !Condition, names_to = "Gene", values_to = "Relative Expression")

ggbarplot(qPCR_summary_Tidy, x = "Gene", y = "Relative Expression",
       add = "mean_se", error.plot = "upper_errorbar", palette = "npg", fill = "Condition", legend.title = "Condition", xlab = "Gene", ylab = "Relative Expression",  position = position_dodge(0.7)) +
   theme_prism(base_size = 14) +
  theme(legend.position = "right", legend.title = element_text()) +
   scale_y_continuous(expand = expansion(mult = c(0, 0.15)))
ggsave('C:/Users/fwestcott/OneDrive - Nexus365/Desktop/Outputs/Transfer-report/Figures/HNM ER Stress genes.png')



```


``` {r Graphs}

ggbarplot(qPCR_summary, x = "Condition", "NFKB1",
       add = "mean_se", error.plot = "upper_errorbar", palette = "npg", legend = "none", fill = "Condition", ylab = "Relative Expression", title = "NFKB1") +
  scale_x_discrete(labels = function(x) str_wrap(x, width = 12)) +
  scale_y_continuous(expand = c(0,0), limits=c(0, 2)) +
theme(axis.text.x = element_text(color = "grey20", size = 12),
axis.text.y = element_text(color = "grey20", size = 16),
axis.title.x = element_text(color = "grey20", size = 18),
axis.title.y = element_text(color = "grey20", size = 18),
plot.title = element_text(color = "grey20", size = 22, face = "bold", hjust = 0.5))
ggsave('C:/Users/fwestcott/OneDrive - Nexus365/Desktop/Results/HNM/Graphs/NFKB1.png')

ggbarplot(qPCR_summary, x = "Condition", "JNK1",
       add = "mean_se", error.plot = "upper_errorbar", palette = "npg", legend = "none", fill = "Condition", ylab = "Relative Expression", title = "JNK1") +
  scale_x_discrete(labels = function(x) str_wrap(x, width = 12)) +
  scale_y_continuous(expand = c(0,0), limits=c(0, 2)) +
theme(axis.text.x = element_text(color = "grey20", size = 12),
axis.text.y = element_text(color = "grey20", size = 16),
axis.title.x = element_text(color = "grey20", size = 18),
axis.title.y = element_text(color = "grey20", size = 18),
plot.title = element_text(color = "grey20", size = 22, face = "bold", hjust = 0.5))
ggsave('C:/Users/fwestcott/OneDrive - Nexus365/Desktop/Results/HNM/Graphs/JNK1.png')

results <- TukeyHSD(aov(JNK2 ~ Condition, data = qPCR_summary))
results_df <- separate(
  as.tibble(results$Condition, rownames = "Condition"), 
  Condition, into = c("group1", "group2"), sep = "-", convert = TRUE)
results_df$p_adj_signif <- if_else(results_df$`p adj` >= 0.05, "ns", 
                                   if_else(results_df$`p adj` >= 0.01, "*", 
                                           if_else(results_df$`p adj` >= 0.001, "**", "***")))
pairwise.test <- filter(results_df, p_adj_signif != 'ns')
pairwise.test <- pairwise.test[c(3,4),]

ggbarplot(qPCR_summary, x = "Condition", "JNK2",
       add = "mean_se", error.plot = "upper_errorbar", palette = "npg", legend = "none", fill = "Condition", ylab = "Relative Expression", title = "JNK2") +
  scale_x_discrete(labels = function(x) str_wrap(x, width = 12)) +
  scale_y_continuous(expand = c(0,0), limits=c(0, 3)) +
theme(axis.text.x = element_text(color = "grey20", size = 12),
axis.text.y = element_text(color = "grey20", size = 16),
axis.title.x = element_text(color = "grey20", size = 18),
axis.title.y = element_text(color = "grey20", size = 18),
plot.title = element_text(color = "grey20", size = 22, face = "bold", hjust = 0.5)) +
    stat_pvalue_manual(pairwise.test, label = "p_adj_signif", y.position = 2.1, step.increase = 0.1)
ggsave('C:/Users/fwestcott/OneDrive - Nexus365/Desktop/Results/HNM/Graphs/JNK2.png')

ggbarplot(qPCR_summary, x = "Condition", "CXCL8",
       add = "mean_se", error.plot = "upper_errorbar", palette = "npg", legend = "none", fill = "Condition", ylab = "Relative Expression", title = "CXCL8") +
  scale_x_discrete(labels = function(x) str_wrap(x, width = 12)) +
  scale_y_continuous(expand = c(0,0), limits=c(0, 4)) +
theme(axis.text.x = element_text(color = "grey20", size = 12),
axis.text.y = element_text(color = "grey20", size = 16),
axis.title.x = element_text(color = "grey20", size = 18),
axis.title.y = element_text(color = "grey20", size = 18),
plot.title = element_text(color = "grey20", size = 22, face = "bold", hjust = 0.5))
ggsave('C:/Users/fwestcott/OneDrive - Nexus365/Desktop/Results/HNM/Graphs/CXCL8.png')

results <- TukeyHSD(aov(CASP3 ~ Condition, data = qPCR_summary))
results_df <- separate(
  as.tibble(results$Condition, rownames = "Condition"), 
  Condition, into = c("group1", "group2"), sep = "-", convert = TRUE)
results_df$p_adj_signif <- if_else(results_df$`p adj` >= 0.05, "ns", 
                                   if_else(results_df$`p adj` >= 0.01, "*", 
                                           if_else(results_df$`p adj` >= 0.001, "**", "***")))
pairwise.test <- filter(results_df, p_adj_signif != 'ns')

ggbarplot(qPCR_summary, x = "Condition", "CASP3",
       add = "mean_se", error.plot = "upper_errorbar", palette = "npg", legend = "none", fill = "Condition", ylab = "Relative Expression", title = "CASP3") +
  scale_x_discrete(labels = function(x) str_wrap(x, width = 12)) +
  scale_y_continuous(expand = c(0,0), limits=c(0, 1.5)) +
theme(axis.text.x = element_text(color = "grey20", size = 12),
axis.text.y = element_text(color = "grey20", size = 16),
axis.title.x = element_text(color = "grey20", size = 18),
axis.title.y = element_text(color = "grey20", size = 18),
plot.title = element_text(color = "grey20", size = 22, face = "bold", hjust = 0.5)) +
    stat_pvalue_manual(pairwise.test, label = "p_adj_signif", y.position = 1.3, step.increase = 0.1)
ggsave('C:/Users/fwestcott/OneDrive - Nexus365/Desktop/Results/HNM/Graphs/CASP3.png')


ggbarplot(qPCR_summary, x = "Condition", "HSPA5",
       add = "mean_se", error.plot = "upper_errorbar", palette = "npg", legend = "none", fill = "Condition", ylab = "Relative Expression", title = "HSPA5") +
  scale_x_discrete(labels = function(x) str_wrap(x, width = 12)) +
  scale_y_continuous(expand = c(0,0), limits=c(0, 2.5)) +
theme(axis.text.x = element_text(color = "grey20", size = 12),
axis.text.y = element_text(color = "grey20", size = 16),
axis.title.x = element_text(color = "grey20", size = 18),
axis.title.y = element_text(color = "grey20", size = 18),
plot.title = element_text(color = "grey20", size = 22, face = "bold", hjust = 0.5))
ggsave('C:/Users/fwestcott/OneDrive - Nexus365/Desktop/Results/HNM/Graphs/HSPA5.png')

ggbarplot(qPCR_summary, x = "Condition", "IL1B",
       add = "mean_se", error.plot = "upper_errorbar", palette = "npg", legend = "none", fill = "Condition", ylab = "Relative Expression", title = "IL1B") +
  scale_x_discrete(labels = function(x) str_wrap(x, width = 12)) +
  scale_y_continuous(expand = c(0,0), limits=c(0, 15)) +
theme(axis.text.x = element_text(color = "grey20", size = 12),
axis.text.y = element_text(color = "grey20", size = 16),
axis.title.x = element_text(color = "grey20", size = 18),
axis.title.y = element_text(color = "grey20", size = 18),
plot.title = element_text(color = "grey20", size = 22, face = "bold", hjust = 0.5))
ggsave('C:/Users/fwestcott/OneDrive - Nexus365/Desktop/Results/HNM/Graphs/IL1B.png')

ggbarplot(qPCR_summary, x = "Condition", "ATF4",
       add = "mean_se", error.plot = "upper_errorbar", palette = "npg", legend = "none", fill = "Condition", ylab = "Relative Expression", title = "ATF4") +
  scale_x_discrete(labels = function(x) str_wrap(x, width = 12)) +
  scale_y_continuous(expand = c(0,0), limits=c(0, 2)) +
theme(axis.text.x = element_text(color = "grey20", size = 12),
axis.text.y = element_text(color = "grey20", size = 16),
axis.title.x = element_text(color = "grey20", size = 18),
axis.title.y = element_text(color = "grey20", size = 18),
plot.title = element_text(color = "grey20", size = 22, face = "bold", hjust = 0.5))
ggsave('C:/Users/fwestcott/OneDrive - Nexus365/Desktop/Results/HNM/Graphs/ATF4.png')

results <- TukeyHSD(aov(ATF6 ~ Condition, data = qPCR_summary))
results_df <- separate(
  as.tibble(results$Condition, rownames = "Condition"), 
  Condition, into = c("group1", "group2"), sep = "-", convert = TRUE)
results_df$p_adj_signif <- if_else(results_df$`p adj` >= 0.05, "ns", 
                                   if_else(results_df$`p adj` >= 0.01, "*", 
                                           if_else(results_df$`p adj` >= 0.001, "**", "***")))
pairwise.test <- filter(results_df, p_adj_signif != 'ns')

ggbarplot(qPCR_summary, x = "Condition", "ATF6",
       add = "mean_se", error.plot = "upper_errorbar", palette = "npg", legend = "none", fill = "Condition", ylab = "Relative Expression", title = "ATF6") +
  scale_x_discrete(labels = function(x) str_wrap(x, width = 12)) +
  scale_y_continuous(expand = c(0,0), limits=c(0, 2)) +
theme(axis.text.x = element_text(color = "grey20", size = 12),
axis.text.y = element_text(color = "grey20", size = 16),
axis.title.x = element_text(color = "grey20", size = 18),
axis.title.y = element_text(color = "grey20", size = 18),
plot.title = element_text(color = "grey20", size = 22, face = "bold", hjust = 0.5)) +
    stat_pvalue_manual(pairwise.test, label = "p_adj_signif", y.position = 1.6, step.increase = 0.1)
ggsave('C:/Users/fwestcott/OneDrive - Nexus365/Desktop/Results/HNM/Graphs/ATF6.png')

ggbarplot(qPCR_summary, x = "Condition", "IL6",
       add = "mean_se", error.plot = "upper_errorbar", palette = "npg", legend = "none", fill = "Condition", ylab = "Relative Expression", title = "IL6") +
  scale_x_discrete(labels = function(x) str_wrap(x, width = 12)) +
  scale_y_continuous(expand = c(0,0), limits=c(0, 15)) +
theme(axis.text.x = element_text(color = "grey20", size = 12),
axis.text.y = element_text(color = "grey20", size = 16),
axis.title.x = element_text(color = "grey20", size = 18),
axis.title.y = element_text(color = "grey20", size = 18),
plot.title = element_text(color = "grey20", size = 22, face = "bold", hjust = 0.5))
ggsave('C:/Users/fwestcott/OneDrive - Nexus365/Desktop/Results/HNM/Graphs/IL6.png')

ggbarplot(qPCR_summary, x = "Condition", "MTOR",
       add = "mean_se", error.plot = "upper_errorbar", palette = "npg", legend = "none", fill = "Condition", ylab = "Relative Expression", title = "MTOR") +
  scale_x_discrete(labels = function(x) str_wrap(x, width = 12)) +
  scale_y_continuous(expand = c(0,0), limits=c(0, 2)) +
theme(axis.text.x = element_text(color = "grey20", size = 12),
axis.text.y = element_text(color = "grey20", size = 16),
axis.title.x = element_text(color = "grey20", size = 18),
axis.title.y = element_text(color = "grey20", size = 18),
plot.title = element_text(color = "grey20", size = 22, face = "bold", hjust = 0.5))
ggsave('C:/Users/fwestcott/OneDrive - Nexus365/Desktop/Results/HNM/Graphs/MTOR.png')

ggbarplot(qPCR_summary, x = "Condition", "ERN1",
       add = "mean_se", error.plot = "upper_errorbar", palette = "npg", legend = "none", fill = "Condition", ylab = "Relative Expression", title = "ERN1") +
  scale_x_discrete(labels = function(x) str_wrap(x, width = 12)) +
  scale_y_continuous(expand = c(0,0), limits=c(0, 2)) +
theme(axis.text.x = element_text(color = "grey20", size = 12),
axis.text.y = element_text(color = "grey20", size = 16),
axis.title.x = element_text(color = "grey20", size = 18),
axis.title.y = element_text(color = "grey20", size = 18),
plot.title = element_text(color = "grey20", size = 22, face = "bold", hjust = 0.5))
ggsave('C:/Users/fwestcott/OneDrive - Nexus365/Desktop/Results/HNM/Graphs/ERN1.png')


```


``` {R Further Stats}

qPCR_summary<- filter(qPCR_summary, qPCR_summary$Condition != "LPS Control")

for (i in 9:ncol(qPCR_summary)) {
   formula <- as.formula(paste(colnames(qPCR_summary)[i], " ~ Insulin * FA_Amount * FA_Type * Round", sep=""))
   model <- aov(formula, data = qPCR_summary)

   cat("\n-----\n\n")
   cat(colnames(qPCR_summary)[i])
   cat("\n")
   print(summary(model))
}

```
